### ISSUE TITLE
Help Need Update

### ISSUE THREAD

**Issue by de2apandi** [slastrina/cdromance_scraper#3]
hello can you update the script i got this error when execution

Scraping: https://cdromance.com/sony-psp-dlc-list-psp-downloadable-content
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cfscrape/__init__.py", line 255, in solve_challenge
    javascript, flags=re.S
AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/cdromance_scraper/scraper.py", line 101, in <module>
    request = scraper.get(content_url)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cfscrape/__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cfscrape/__init__.py", line 204, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "/usr/local/lib/python3.7/dist-packages/cfscrape/__init__.py", line 292, in solve_challenge
    % BUG_REPORT
ValueError: Unable to identify Cloudflare IUAM Javascript on website. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."

**Comment by slastrina** [comment]
Hi, cdromance has changed its API along and cloudflair also adds its own challenges, i dont have any intention to maintain the code in this repo, i left it here as a code reference for devs. 

you are welcome to attempt to fix it and raise a pull request against this repo if you wish, but i won't personally be putting any additional effort into the script.
